spring.application.name=practice
RestAssured_BaseURI = http://216.10.245.166

# ----- Chat GPT Configurations---------
API_KEY= Bearer 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
MAX_TOKEN= 50
CHAT_MODEL= gpt-4o-mini